# There's no sudo: required because it slows down Travis CI job startup
# and we don't really need it with addons: apt.

language: python

dist: trusty

python:
  - "2.7"

install:
  - pip install pylint tox tornado scapy
  - python setup.py install

# We need system's site_packages for python-dbus.
virtualenv:
    system_site_packages: true

script:
  - export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
  - pylint --errors-only wifiphisher
  - tox -e ALL

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always

  irc:
    channels:
      - "chat.freenode.net#wifiphisher"
    use_notice: true

# FIXME: python-tornado is here because of this error:
#
# > Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+
# > (although some distributions have backported the necessary changes to older
# > versions)
#
# Ubuntu does the backporting. The proper solution would be to upgrade Python
# or somehow bypass this Tornado check (or use an older Tornado version
# perhaps?)

addons:
    apt:
        packages:
          - hostapd
          - dnsmasq
          - python-dbus
          - libdbus-1-dev
          - libdbus-glib-1-dev
